[package]
name = "fltk-form-derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "fltk_form_derive"
path = "src/lib.rs"
proc-macro = true

[dependencies]
syn = "1"
quote = "1"
proc-macro2 = "1.0"